### PR TITLE
fix(pkg/cache): Increase the wait time around asynchronous logic

### LINKED ISSUE #314: Some tests seem to be non deterministic and sometimes broken
Sometimes running `go test ./pkg/cache/ -run TestGetNarInfo -v ` makes it fail. I haven't investigated why.

<details>

  ```
=== RUN   TestGetNarInfoWithoutSignature
=== PAUSE TestGetNarInfoWithoutSignature
=== RUN   TestGetNarInfo
    cache_test.go:295: /nix/store/g1z2c7x7mj9za56yxcg4qmrdhnp91hfg-dbmate-2.27.0/bin/dbmate --url=sqlite:/tmp/cache-path-2719774178/var/ncps/db/db.sqlite --migrations-dir=/home/ccr/projects/aciceri/ncps/db/migrations --schema-file=/home/ccr/projects/aciceri/ncps/db/schema.sql up: Creating: /tmp/cache-path-2719774178/var/ncps/db/db.sqlite
        Applying: 20241210054814_create-narinfos-table.sql
        Applied: 20241210054814_create-narinfos-table.sql in 327.206µs
        Applying: 20241210054829_create-nars-table.sql
        Applied: 20241210054829_create-nars-table.sql in 322.267µs
        Applying: 20241213014846_add-query-to-nars-table.sql
        Applied: 20241213014846_add-query-to-nars-table.sql in 260.049µs
=== RUN   TestGetNarInfo/narinfo_does_not_exist_upstream
=== RUN   TestGetNarInfo/narinfo_exists_upstream
=== RUN   TestGetNarInfo/narinfo_exists_upstream/narinfo_does_not_exist_in_storage_yet
=== RUN   TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_storage_yet
=== RUN   TestGetNarInfo/narinfo_exists_upstream/narinfo_does_not_exist_in_the_database_yet
=== RUN   TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_the_database_yet
=== RUN   TestGetNarInfo/narinfo_exists_upstream/size_is_correct
=== RUN   TestGetNarInfo/narinfo_exists_upstream/it_should_now_exist_in_the_store
=== RUN   TestGetNarInfo/narinfo_exists_upstream/it_should_be_signed_by_our_server
=== RUN   TestGetNarInfo/narinfo_exists_upstream/it_should_not_be_signed_twice_by_our_server
=== RUN   TestGetNarInfo/narinfo_exists_upstream/it_should_have_also_pulled_the_nar
    cache_test.go:459: 
        	Error Trace:	/home/ccr/projects/aciceri/ncps/pkg/cache/cache_test.go:459
        	Error:      	Received unexpected error:
        	           	stat /tmp/cache-path-2719774178/store/nar/1/1x/1xqqdh1yn5sz3d6wcz3qz3azm5mbypwq6mv8g2dal1v042h0sprf.nar.xz: no such file or directory
        	Test:       	TestGetNarInfo/narinfo_exists_upstream/it_should_have_also_pulled_the_nar
=== RUN   TestGetNarInfo/narinfo_exists_upstream/narinfo_does_exist_in_the_database,_and_has_initial_last_accessed_at
=== RUN   TestGetNarInfo/narinfo_exists_upstream/nar_does_exist_in_the_database,_and_has_initial_last_accessed_at
=== RUN   TestGetNarInfo/narinfo_exists_upstream/pulling_it_another_time_within_recordAgeIgnoreTouch_should_not_update_last_accessed_at
=== RUN   TestGetNarInfo/narinfo_exists_upstream/pulling_it_another_time_within_recordAgeIgnoreTouch_should_not_update_last_accessed_at/narinfo_does_exist_in_the_database_with_the_same_last_accessed_at
=== RUN   TestGetNarInfo/narinfo_exists_upstream/pulling_it_another_time_should_update_last_accessed_at_only_for_narinfo
=== RUN   TestGetNarInfo/narinfo_exists_upstream/pulling_it_another_time_should_update_last_accessed_at_only_for_narinfo/narinfo_does_exist_in_the_database,_and_has_more_recent_last_accessed_at
=== RUN   TestGetNarInfo/narinfo_exists_upstream/no_error_is_returned_if_the_entry_already_exist_in_the_database
=== RUN   TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_storage,_it_gets_pulled_automatically
=== RUN   TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_storage,_it_gets_pulled_automatically/it_should_not_return_an_error
=== RUN   TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_storage,_it_gets_pulled_automatically/it_should_have_also_pulled_the_nar
    cache_test.go:625: 
        	Error Trace:	/home/ccr/projects/aciceri/ncps/pkg/cache/cache_test.go:625
        	Error:      	Received unexpected error:
        	           	stat /tmp/cache-path-2719774178/store/nar/1/1x/1xqqdh1yn5sz3d6wcz3qz3azm5mbypwq6mv8g2dal1v042h0sprf.nar.xz: no such file or directory
        	Test:       	TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_storage,_it_gets_pulled_automatically/it_should_have_also_pulled_the_nar
=== RUN   TestGetNarInfo/narinfo_with_transparent_encryption
=== RUN   TestGetNarInfo/narinfo_with_transparent_encryption/nar_idx0_narInfoHash=jiwdym6f9w6v5jcbqf5wn7fmg11v5q0j
--- FAIL: TestGetNarInfo (2.06s)
    --- PASS: TestGetNarInfo/narinfo_does_not_exist_upstream (0.00s)
    --- FAIL: TestGetNarInfo/narinfo_exists_upstream (2.03s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/narinfo_does_not_exist_in_storage_yet (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_storage_yet (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/narinfo_does_not_exist_in_the_database_yet (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_the_database_yet (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/size_is_correct (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/it_should_now_exist_in_the_store (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/it_should_be_signed_by_our_server (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/it_should_not_be_signed_twice_by_our_server (0.00s)
        --- FAIL: TestGetNarInfo/narinfo_exists_upstream/it_should_have_also_pulled_the_nar (0.01s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/narinfo_does_exist_in_the_database,_and_has_initial_last_accessed_at (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/nar_does_exist_in_the_database,_and_has_initial_last_accessed_at (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/pulling_it_another_time_within_recordAgeIgnoreTouch_should_not_update_last_accessed_at (1.00s)
            --- PASS: TestGetNarInfo/narinfo_exists_upstream/pulling_it_another_time_within_recordAgeIgnoreTouch_should_not_update_last_accessed_at/narinfo_does_exist_in_the_database_with_the_same_last_accessed_at (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/pulling_it_another_time_should_update_last_accessed_at_only_for_narinfo (1.00s)
            --- PASS: TestGetNarInfo/narinfo_exists_upstream/pulling_it_another_time_should_update_last_accessed_at_only_for_narinfo/narinfo_does_exist_in_the_database,_and_has_more_recent_last_accessed_at (0.00s)
        --- PASS: TestGetNarInfo/narinfo_exists_upstream/no_error_is_returned_if_the_entry_already_exist_in_the_database (0.00s)
        --- FAIL: TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_storage,_it_gets_pulled_automatically (0.01s)
            --- PASS: TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_storage,_it_gets_pulled_automatically/it_should_not_return_an_error (0.00s)
            --- FAIL: TestGetNarInfo/narinfo_exists_upstream/nar_does_not_exist_in_storage,_it_gets_pulled_automatically/it_should_have_also_pulled_the_nar (0.01s)
    --- PASS: TestGetNarInfo/narinfo_with_transparent_encryption (0.02s)
        --- PASS: TestGetNarInfo/narinfo_with_transparent_encryption/nar_idx0_narInfoHash=jiwdym6f9w6v5jcbqf5wn7fmg11v5q0j (0.02s)
=== CONT  TestGetNarInfoWithoutSignature
    cache_test.go:243: /nix/store/g1z2c7x7mj9za56yxcg4qmrdhnp91hfg-dbmate-2.27.0/bin/dbmate --url=sqlite:/tmp/cache-path-1540712501/var/ncps/db/db.sqlite --migrations-dir=/home/ccr/projects/aciceri/ncps/db/migrations --schema-file=/home/ccr/projects/aciceri/ncps/db/schema.sql up: Creating: /tmp/cache-path-1540712501/var/ncps/db/db.sqlite
        Applying: 20241210054814_create-narinfos-table.sql
        Applied: 20241210054814_create-narinfos-table.sql in 361.53µs
        Applying: 20241210054829_create-nars-table.sql
        Applied: 20241210054829_create-nars-table.sql in 312.197µs
        Applying: 20241213014846_add-query-to-nars-table.sql
        Applied: 20241213014846_add-query-to-nars-table.sql in 261.071µs
--- PASS: TestGetNarInfoWithoutSignature (0.02s)
FAIL
FAIL	github.com/kalbasit/ncps/pkg/cache	2.125s
FAIL
  ```
</details>

While sometimes running the test with `go test` seems to work running `nix build github:kalbasit/ncps` (current `main` is `f5842c9`) always fails on my machine.

<details>

  ```
ncps-f5842c9> Running phase: unpackPhase
ncps-f5842c9> unpacking source archive /nix/store/m6siyf51s1w3d9lpvvmznbfaqz6xj4in-source
ncps-f5842c9> source root is source
ncps-f5842c9> Running phase: patchPhase
ncps-f5842c9> Running phase: updateAutotoolsGnuConfigScriptsPhase
ncps-f5842c9> Running phase: configurePhase
ncps-f5842c9> Running phase: buildPhase
ncps-f5842c9> Building subPackage .
ncps-f5842c9> Building subPackage ./cmd
ncps-f5842c9> Building subPackage ./pkg/cache
ncps-f5842c9> Building subPackage ./pkg/cache/healthcheck
ncps-f5842c9> Building subPackage ./pkg/cache/upstream
ncps-f5842c9> Building subPackage ./pkg/database
ncps-f5842c9> Building subPackage ./pkg/helper
ncps-f5842c9> Building subPackage ./pkg/nar
ncps-f5842c9> Building subPackage ./pkg/nixcacheinfo
ncps-f5842c9> Building subPackage ./pkg/otelzerolog
ncps-f5842c9> Building subPackage ./pkg/prometheus
ncps-f5842c9> Building subPackage ./pkg/server
ncps-f5842c9> Building subPackage ./pkg/storage
ncps-f5842c9> Building subPackage ./pkg/storage/local
ncps-f5842c9> Building subPackage ./pkg/telemetry
ncps-f5842c9> Building subPackage ./testhelper
ncps-f5842c9> Running phase: checkPhase
ncps-f5842c9> --- FAIL: TestGetNar (2.04s)
ncps-f5842c9>     cache_test.go:889: /nix/store/g1z2c7x7mj9za56yxcg4qmrdhnp91hfg-dbmate-2.27.0/bin/dbmate --url=sqlite:/build/cache-path-3207139656/var/ncps/db/db.sqlite --migrations-dir=/build/source/db/migrations --schema-file=/build/source/db/schema.sql up: Creating: /build/cache-path-3207139656/var/ncps/db/db.sqlite
ncps-f5842c9>         Applying: 20241210054814_create-narinfos-table.sql
ncps-f5842c9>         Applied: 20241210054814_create-narinfos-table.sql in 2.441643ms
ncps-f5842c9>         Applying: 20241210054829_create-nars-table.sql
ncps-f5842c9>         Applied: 20241210054829_create-nars-table.sql in 3.493141ms
ncps-f5842c9>         Applying: 20241213014846_add-query-to-nars-table.sql
ncps-f5842c9>         Applied: 20241213014846_add-query-to-nars-table.sql in 2.374878ms
ncps-f5842c9>     --- FAIL: TestGetNar/nar_exists_upstream (2.02s)
ncps-f5842c9>         --- FAIL: TestGetNar/nar_exists_upstream/size_is_correct (0.00s)
ncps-f5842c9>             cache_test.go:948:
ncps-f5842c9>                   Error Trace:    /build/source/pkg/cache/cache_test.go:948
ncps-f5842c9>                   Error:          Not equal:
ncps-f5842c9>                                   expected: 50160
ncps-f5842c9>                                   actual  : -1
ncps-f5842c9>                   Test:           TestGetNar/nar_exists_upstream/size_is_correct
ncps-f5842c9>         --- FAIL: TestGetNar/nar_exists_upstream/it_should_now_exist_in_the_store (0.00s)
ncps-f5842c9>             cache_test.go:961:
ncps-f5842c9>                   Error Trace:    /build/source/pkg/cache/cache_test.go:961
ncps-f5842c9>                   Error:          unable to find file "/build/cache-path-3207139656/store/nar/1/1l/1lid9xrpirkzcpqsxfq02qwiq0yd70chfl860wzsqd1739ih0nri.nar.xz"
ncps-f5842c9>                   Test:           TestGetNar/nar_exists_upstream/it_should_now_exist_in_the_store
ncps-f5842c9> --- FAIL: TestRunLRU (1.11s)
ncps-f5842c9>     cache_internal_test.go:161: /nix/store/g1z2c7x7mj9za56yxcg4qmrdhnp91hfg-dbmate-2.27.0/bin/dbmate --url=sqlite:/build/cache-path-4185378079/var/ncps/db/db.sqlite --migrations-dir=/build/source/db/migrations --schema-file=/build/source/db/schema.sql up: Creating: /build/cache-path-4185378079/var/ncps/db/db.sqlite
ncps-f5842c9>         Applying: 20241210054814_create-narinfos-table.sql
ncps-f5842c9>         Applied: 20241210054814_create-narinfos-table.sql in 7.380263ms
ncps-f5842c9>         Applying: 20241210054829_create-nars-table.sql
ncps-f5842c9>         Applied: 20241210054829_create-nars-table.sql in 4.87981ms
ncps-f5842c9>         Applying: 20241213014846_add-query-to-nars-table.sql
ncps-f5842c9>         Applied: 20241213014846_add-query-to-nars-table.sql in 5.558016ms
ncps-f5842c9>     cache_internal_test.go:241:
ncps-f5842c9>           Error Trace:    /build/source/pkg/cache/cache_internal_test.go:241
ncps-f5842c9>           Error:          Should be true
ncps-f5842c9>           Test:           TestRunLRU
ncps-f5842c9>           Messages:       confirm all nars are in the store
ncps-f5842c9>     cache_internal_test.go:241:
ncps-f5842c9>           Error Trace:    /build/source/pkg/cache/cache_internal_test.go:241
ncps-f5842c9>           Error:          Should be true
ncps-f5842c9>           Test:           TestRunLRU
ncps-f5842c9>           Messages:       confirm all nars are in the store
ncps-f5842c9> FAIL
ncps-f5842c9> FAIL      github.com/kalbasit/ncps/pkg/cache      5.656s
ncps-f5842c9> FAIL
error: Cannot build '/nix/store/3cf9zk7m8j5bdqar57fj6rzmmlp74fga-ncps-f5842c9.drv'.
       Reason: builder failed with exit code 1.
       Output paths:
         /nix/store/fw297pi3ndf086sc6gd2k4hqlz4j7rq1-ncps-f5842c9
       Last 25 log lines:
       >             cache_test.go:961:
       >                         Error Trace:    /build/source/pkg/cache/cache_test.go:961
       >                       Error:          unable to find file "/build/cache-path-3207139656/store/nar/1/1l/1lid9xrpirkzcpqsxfq02qwiq0yd70chfl860wzsqd1739ih0nri.nar.xz"
       >                   Test:           TestGetNar/nar_exists_upstream/it_should_now_exist_in_the_store
       > --- FAIL: TestRunLRU (1.11s)
       >     cache_internal_test.go:161: /nix/store/g1z2c7x7mj9za56yxcg4qmrdhnp91hfg-dbmate-2.27.0/bin/dbmate --url=sqlite:/build/cache-path-4185378079/var/ncps/db/db.sqlite --migrations-dir=/build/source/db/migrations --schema-file=/build/source/db/schema.sql up: Creating: /build/cache-path-4185378079/var/ncps/db/db.sqlite
       >         Applying: 20241210054814_create-narinfos-table.sql
       >         Applied: 20241210054814_create-narinfos-table.sql in 7.380263ms
       >         Applying: 20241210054829_create-nars-table.sql
       >         Applied: 20241210054829_create-nars-table.sql in 4.87981ms
       >         Applying: 20241213014846_add-query-to-nars-table.sql
       >         Applied: 20241213014846_add-query-to-nars-table.sql in 5.558016ms
       >     cache_internal_test.go:241:
       >           Error Trace:    /build/source/pkg/cache/cache_internal_test.go:241
       >              Error:          Should be true
       >          Test:           TestRunLRU
       >              Messages:       confirm all nars are in the store
       >     cache_internal_test.go:241:
       >               Error Trace:    /build/source/pkg/cache/cache_internal_test.go:241
       >              Error:          Should be true
       >          Test:           TestRunLRU
       >              Messages:       confirm all nars are in the store
       > FAIL
       > FAIL     github.com/kalbasit/ncps/pkg/cache      5.656s
       > FAIL
       For full logs, run:
         nix log /nix/store/3cf9zk7m8j5bdqar57fj6rzmmlp74fga-ncps-f5842c9.drv
```
</details>

Notice that in derivation the failing tests are different

I can imagine that the CI checks are good because it uses a cache and for some reason (race condition?) the first time it built the current derivation it worked? It's still weird...

@kalbasit

### PR DESCRIPTION
**Pull request by kalbasit**
These tests depends on other factors (such as CPU speed, system loadavg, etc..) and assume a very quick runtime. Wait a total of ~5s in increasingly small increments to allow for the test to finish quicly while waiting for a slow system to finish.

fixes #314

### CODE REVIEW

File: pkg/cache/cache_test.go [hunk 1]
```diff
@@ -958,7 +973,21 @@ func TestGetNar(t *testing.T) {
 		})
 
 		t.Run("it should now exist in the store", func(t *testing.T) {
-			assert.FileExists(t, filepath.Join(dir, "store", "nar", testdata.Nar1.NarPath))
+			// Force the other goroutine to run so it actually download the file
+			// Try at least 10 times before announcing an error
```
Comment (kalbasit) [inline pkg/cache/cache_test.go]:
```suggestion
```
